### PR TITLE
Get an almost-executable-query

### PR DESCRIPTION
**Pull request by gepser**
You shoul have almost an executable query, for example:

sql.query
// insert into users (name, lastname, age, gender) values ($p1, $p2, 24, $p3);

sql.values
// { p1: 'John', p2: 'Snow', p3: 'male' }

sql.replaceDolarQuery
// insert into users (name, lastname, age, gender) values ($John$, $Snow$, 24, $male$);

And then you just have to do a simple replace when you send that query to be executed. 

Something like this:

console.log(sql.replaceDolarQuery.replace(/\$/g,"'"));
// insert into users (name, lastname, age, gender) values ('John', 'Snow', 24, 'male');

### CODE REVIEW

**Comment by okv** [comment]
@gepser why you need this changes? What is the motivation?

**Comment by artzhuchka** [comment]
It seems for me that this issue is very similar to https://github.com/2do2go/json-sql/issues/1.
You can use option `separatedValues: false` to get plain sql-query without placeholders.

Example:
```javascript
var jsonSql = require('json-sql')({separatedValues: false});

var sql = jsonSql.build({
	type: 'update',
	table: 'users',
	condition: {name: 'John'},
	modifier: {name: 'Peter'}
});

sql.query
// 'update "users" set "name" = \'Peter\' where "name" = \'John\';'
```

**Comment by gepser** [comment]
Hi, this was my motivation:
http://stackoverflow.com/questions/26497158/sql-statement-doesnt-make-sense/30655609#30655609

and I did use "dolar" in order to not include single quotes.

But you are right, this pull request is very similar to the other one and I didn't know about that.

Your module is very useful, thanks for that, all it needs is some documentation, do you have plans for that? I can help you if you want.

**Comment by okv** [comment]
We'll try start working on docs soon. Sometimes it's just hard to start ... =)

**Comment by okv** [comment]
documentation now available at [docs](../tree/master/docs) page

**Pull request closed without merging**
